uclient-fetch: fix statement may fallt hrough
Fixes following issue reported by clang-12 static analyzer:

 uclient-fetch.c:228:6: error: this statement may fall through [-Werror=implicit-fallthrough=]
    if (sscanf(blobmsg_get_string(tb[H_RANGE]),
       ^
 uclient-fetch.c:236:2: note: here
   case 204:
   ^~~~

Signed-off-by: Petr Štetiar <ynezz@true.cz>
(cherry picked from commit 66b4420856a7eb2c5a9f9a7acdb7e796ed807b17)